### ISSUE TITLE
Cannot get Claude models to work

### ISSUE THREAD

**Issue by takeoffnetworks** [MadcowD/ell#149] opened 2024-09-11 10:22 UTC
I tried without specifying the client and then by specifically including the anthropic client but does not work in both cases.

File "<xxx>/.venv/lib/python3.11/site-packages/ell/lmp/complex.py", line 243, in model_call
    (result, _api_params, metadata) = call(model=model, messages=messages, api_params={**config.default_lm_params, **api_params, **lm_params}, client=client or default_client_from_decorator, _invocation_origin=_invocation_origin, _exempt_from_tracking=exempt_from_tracking, _logging_color=color, _name=prompt.__name__, tools=tools)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<xxxx/.venv/lib/python3.11/site-packages/ell/util/api.py", line 83, in call
    model_call = client.chat.completions.create
                 ^^^^^^^^^^^
AttributeError: 'Anthropic' object has no attribute 'chat'

**Comment by simpthy** [comment] 2024-09-11 15:46
This seems like it might be a dupe of: https://github.com/MadcowD/ell/issues/56

**Comment by emfastic** [comment] 2024-09-14 17:19
@takeoffnetworks can you confirm it's working for you now? it's implemented

**Comment by MadcowD** [comment] 2024-09-17 18:14
Yes please try
```
pip install --upgrade ell-ai
```
:)

**Closed by MadcowD** 2024-09-17 18:14 UTC

**Comment by takeoffnetworks** [comment] 2024-09-18 09:44
Tested at my end and this works perfectly with claude sonnet. Thanks for this update
